/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 fox.glb --transform 
Files: fox.glb [90.18MB] > C:\Users\MUDIT BHATNAJAR\Desktop\ecoquest\fox-transformed.glb [2.55MB] (97%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

export function Model(props: any) {
  const { nodes, materials } = useGLTF('/fox-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={(nodes.Sphere as THREE.Mesh).geometry} material={materials.PaletteMaterial001} position={[0.136, 6.757, 1.017]} scale={[1.813, 1.813, 1.502]} />
      <mesh geometry={(nodes.Sphere001 as THREE.Mesh).geometry} material={(nodes.Sphere001 as THREE.Mesh).material} position={[0.148, 6.718, -0.437]} rotation={[-Math.PI, 0, 0]} scale={[0.572, 0.456, 0.809]} />
    </group>
  )
}; export default Model;

useGLTF.preload('/fox-transformed.glb');
